language: node_js
node_js:
  - '6.5.0'
script:
  # build
  - npm run release
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  email: $GITHUB_MAIL

branches:
  only:
    - master
notification:
  email:
    - ${GITHUB_MAIL}
  on_success: always
